spring:
  application:
    name: auth-application
  data:
    mongodb:
      uri: mongodb://localhost:27017/authdb
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
