spring:
  application:
    name: student-application
  data:
    mongodb:
      uri: mongodb://localhost:27017/studentdb
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
